### ISSUE TITLE
インデント揃ってない

### ISSUE THREAD

**Issue by ladnack** [ookamiinc/rails_tutorial_app#1]
https://github.com/ookamiinc/rails_tutorial_app/blob/039ae726eafd098942f959693e76343efef66c67/config/routes.rb#L10-L25

**Comment by ladnack** [comment]
@19960117yusuke 

複数箇所あるから直しておこうか！

https://github.com/ookamiinc/rails_tutorial_app/blob/039ae726eafd098942f959693e76343efef66c67/app/controllers/users_controller.rb#L33-L51

**Comment by ladnack** [comment]
Ruby Style Guide https://github.com/rubocop-hq/ruby-style-guide

ざっとcode部分だけでも目通しとくいいね

**Comment by 19960117yusuke** [comment]
ありがとうございます！
今から読みます！

**Comment by ladnack** [comment]
ookamiのプロジェクトでも使ってやつ `rubocop`
 
- https://qiita.com/yaotti/items/4f69a145a22f9c8f8333
- https://github.com/rubocop-hq/rubocop

これ入れてみようか！

```ruby
group :development do
  gem 'web-console',           '3.5.1'
  gem 'listen',                '3.1.5'
  gem 'spring',                '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
  gem 'rubocop', require: false  # <--追加
end
```

こんな感じで追加して以下を実行

```
$ bundle install
```

さらに以下を実行すると、勝手に色々直してくれる

```
$ bundle exec rubocop -a
```

**Comment by 19960117yusuke** [comment]
https://www.granfairs.com/blog/staff/git-commit-fix

上記を参考に、commit名を変更します。

**Comment by ladnack** [comment]
一度pushしたコミットを改変したあとは、`--forse-with-lease` オプションをつけてpushして下さい
安全に強制上書きしてくれます

`$ git push --forse-with-lease origin {branch_name}`

**Comment by 19960117yusuke** [comment]
了解です。
今後そのようにします。

**Comment by ladnack** [comment]
Install rubocop #4 でだいたい直ってるのOK👍
