### ISSUE TITLE
アプリ追加機能一覧

### ISSUE THREAD

**Issue by 19960117yusuke** [ookamiinc/rails_tutorial_app#11]
**アプリでやりたいこと**

- 日常系 (仕事によって、職場外でも繋がれる→励まし、共感、motivated)
1.いいね機能
2.返信
3.(ライバル機能)ーなんか面白い機能探し中。
- 情報共有 (最新の情報がこのアプリでアクセスできる。)
1.リンクのOGPまで載せる
2.いいね機能と情報保存を分けた方がいいかも
3.プロフィール文の設置
4.コンテンツ、ユーザーの検索機能
5.情報保存が多い投稿については、自動でfeedに出てくる
ユーザーは自分の職業を登録(エンジニアなど)
同じ職業の人が50人以上「情報保存」している投稿は自動的に、その職業の人に全発信
- 採用系 (日常的な、気軽な形での採用募集)

ログイン機能
通知機能
DM機能
コンテンツを読み込んで、禁止ワードを含んだ言葉を削除する機能。(DB段階でいいかも)

**Comment by ladnack** [comment]
## 全体
* 全体的にindent等揃えて
* バナーは時間で消えた方が良い

<img width="1160" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389869-1130e36c-6fce-11e8-9059-bf12a8b91ca6.png">


* Follow, Unfollowクリックしてもリロードしないと表示変わらない

<img width="1178" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389887-269bf11a-6fce-11e8-92b3-dc712773c7b8.png">
<img width="778" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389901-3774cafc-6fce-11e8-871a-04a0fdad2dd7.png">



* 別ユーザーなので、view my profileは文言変えたい

<img width="284" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389908-3f2c1124-6fce-11e8-8ebd-e95697b054c7.png">


## いいね
* データは作成されるが、表示は更新されない
* Microposts と Favorites の間区別したい

<img width="797" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389919-4ea7a24e-6fce-11e8-9428-a84c794f7505.png">


* 表示するmicropost分だけlikesに対するクエリが発行される

<img width="1231" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389957-6cfbc630-6fce-11e8-9dd4-df0f6c44c5c9.png">


* 他のユーザーのFavoriteは文言変えたい

<img width="1183" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389964-79026e3e-6fce-11e8-8faa-29aa933da012.png">


## 検索
* 何の検索かわからない
	* placeholderとか
	* 配置変えても良いかも
	* サイズ調整したいね

<img width="1189" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389968-83775992-6fce-11e8-91e4-394821039915.png">


## Reply

* 機能してしてない

<img width="1173" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389979-8ce196f0-6fce-11e8-9bf3-8ec9e2973e4b.png">

<img width="1036" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389975-89ae1670-6fce-11e8-9545-6ddabc60722c.png">


## DM
* 自分へのDMはいらない
	* DM送ったユーザーの一覧表示とか

<img width="319" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389988-99340230-6fce-11e8-802b-dd5a34c23a84.png">

**Comment by 19960117yusuke** [comment]
ありがとうございます！
直します！

**Comment by 19960117yusuke** [comment]
メモ

micropostのコンテントが作成できない謎エラー

**Comment by ladnack** [comment]
@19960117yusuke 

https://github.com/ookamiinc/rails_tutorial_app/issues/11#issue-330850580 のどこまで完成させるか再度共有お願いします🙏

実装した機能については、最低限動くことは保証されるように

**Comment by 19960117yusuke** [comment]
@ladnack 
下記の予定です。

期日までに、

アプリで最低実装すること
1.いいね機能
2.ポストへの返信機能
3.プロフィール文の設置
4.コンテンツの検索機能
5.twitterログイン機能
6.DM機能

========================
余力があればやること
1.Postのなかにリンクがある時に、リンクの形式にする。
2.いいねが10以上の投稿はfeedに自動で出てくる。
3.通知機能(いいね、返信、DM)
4,コンテンツの禁止ワードを含んだ言葉を削除する機能。(DBのvalidation)

**Comment by 19960117yusuke** [comment]
## 全体
* 全体的にindent等揃えて










* 表示するmicropost分だけlikesに対するクエリが発行される

<img width="1231" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389957-6cfbc630-6fce-11e8-9dd4-df0f6c44c5c9.png">





## 検索
* 何の検索かわからない
	* placeholderとか
	* 配置変えても良いかも
	* サイズ調整したいね

<img width="1189" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389968-83775992-6fce-11e8-91e4-394821039915.png">




## DM
* 自分へのDMはいらない
	* DM送ったユーザーの一覧表示とか

<img width="319" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41389988-99340230-6fce-11e8-802b-dd5a34c23a84.png">

**Comment by ladnack** [comment]
@19960117yusuke 
各issueのまとめを書いてそれぞれcloseお願いします！
