### ISSUE TITLE
コンテンツへのいいね機能の実装

### ISSUE THREAD

**Issue by 19960117yusuke** [ookamiinc/rails_tutorial_app#12]
マイクロポストにいいね機能をつける。micropostでは、いくつのファボがついたかを表示、userはお気に入り登録したものを特定のURLで閲覧可能。

- DB
    -  LikeTableの作成。(名称あっているかな)
        - indexは必要
- Model
    -  アソシエーション。(micropost,user,like)
- View
    -  お気に入りフォーム、お気に入り数の表示
　    - _micropost.html.erb
    -  userのお気に入りの閲覧
          -  お気に入りへの導線
               -  users#show
    　   -   お気に入りページ
　　　　- users/:id/like
- Controller
    -  Likes#create,destroy
    -  users#like

===
追加して、
・誰にファボを押されたか
・保存するものと単なるファボを分ける

の２つの機能も余裕あればつける。

**Comment by 19960117yusuke** [comment]
ありがとうございます！それですね。

**Comment by 19960117yusuke** [comment]
![2018-06-10 0 11 24](https://user-images.githubusercontent.com/35832220/41193091-eed5a4f8-6c42-11e8-845c-691cd2620658.png)
![2018-06-10 0 11 18](https://user-images.githubusercontent.com/35832220/41193092-ef050d38-6c42-11e8-9c59-9d51d67e9526.png)
![2018-06-10 0 11 01](https://user-images.githubusercontent.com/35832220/41193093-ef2cb180-6c42-11e8-97f5-71a2f0d2dfee.png)

- 現状行ったプルリクエスト

Postごとにlikeボタンがある。
押すと、お気に入りに登録できる。
user#showにお気に入り一覧への導線あり。
お気に入り一覧users#likesの画面。

- 残タスク

likeボタンを星型にする
likeボタンに、合計何ファボあるのか表示
likeを押した華道家で表示の変更。
お気に入りのdeleteもできるように。
ajaxを取り入れて、非同期処理に。
user#show,users#likesのcss整形。

**Comment by 19960117yusuke** [comment]
更新

- 現状行ったプルリクエスト

Postごとにlikeボタンがある。
押すと、お気に入りに登録できる。
user#showにお気に入り一覧への導線あり。
お気に入り一覧users#likesの画面。
users#likesのcss整形。
likeボタンに、合計何ファボあるのか表示
likeを押した華道家で表示の変更。
お気に入りのdeleteもできるように。

- 残タスク

likeボタンを星型にする
ajaxを取り入れて、非同期処理に。
user#showのcss整形。

**Comment by ladnack** [comment]
`- [ ] todo1`でcheck list作れるよ

- [ ] todo1
- [ ] todo2

**Comment by 19960117yusuke** [comment]
メモ
 - Ajaxでclass自体は変わっている
→なぜ、色が変わらないのか。全体的にcSSがうまく適用されていないのかも。原因を空いているときに調べる。

 - <%= micropost.users.count %>もうまく、セレクタを指定してあげれば変えることは可能。
→ので、また変えよう。

**Comment by 19960117yusuke** [comment]
できたこと
-いいね!ボタンをハートマークに
-いいねの件数を取得する
-上記にajaxを取り入れる（現在はコメントアウト中)
-fav欄を閲覧できる

できなかったこと
-ajaxを取り入れる際、ハートマークの色変更がスムーズに動作しない（一度ハートマーク以外のところを押す必要がある。
