### ISSUE TITLE
Git講座

### ISSUE THREAD

**Issue by ladnack** [ookamiinc/rails_tutorial_app#20]
- Gitの操作に慣れて開発効率を上げる🚀

**Comment by ladnack** [comment]
### gitコマンドのailasを設定

https://git-scm.com/book/ja/v2/Git-の基本-Git-エイリアス

**Comment by ladnack** [comment]
### rebaseを使う

https://git-scm.com/book/ja/v1/Git-のブランチ機能-リベース

**Comment by 19960117yusuke** [comment]
自分用メモ
https://qiita.com/19960117yusuke/items/f35c924f269d24925863

あとで形式修正。
