### ISSUE TITLE
Twitter連携ログイン機能

### ISSUE THREAD

**Issue by 19960117yusuke** [ookamiinc/rails_tutorial_app#26]
明日作成。

**Comment by 19960117yusuke** [comment]
メモ
https://qiita.com/keeya/items/c96a0393c76f5560ee41
https://qiita.com/puremoru0315/items/f1d459b663fd3b715dee


上記2ファイルを参照。
単なる実装ではなく、できればAPIについての知識もつけるところまでを目標に。

omniauth.rbの設定までdone

**Comment by 19960117yusuke** [comment]
試しにtest_appで作成。

![2018-06-12 18 22 54](https://user-images.githubusercontent.com/35832220/41281948-b0d94646-6e6d-11e8-9498-b354eeb09dc9.png)

**Comment by ladnack** [comment]
@19960117yusuke 

コメント削除してみて
 `#providerはどのサービ...`

**Comment by 19960117yusuke** [comment]
ありがとうございます。

コメント消しはやったのですが、syntaxエラーですね。。。。(サーバー再起動もしました。)



class User < ApplicationRecord

  def self.find_or_create_from_auth_hash(auth_hash)
   provider = auth_hash[:provider]　
   name = auth_hash[:info][:name]
   image_url = auth_hash[:info][:image]

   self.find_or_create_by(provider: provider,uid: uid) do |user|
     user.user_name = name
     user.image_url = image_url
   end
  end

end

**Comment by 19960117yusuke** [comment]
![2018-06-13 19 33 59](https://user-images.githubusercontent.com/35832220/41346178-c079da38-6f40-11e8-889f-b9f5d5d56467.png)

**Comment by ladnack** [comment]
@19960117yusuke 

`provider = auth_hash[:provider]` の後ろの全角スペース入ってた

**Comment by ladnack** [comment]
構文チェックするパッケージ入れると良いかもね

<img width="541" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41346354-3b7047e0-6f41-11e8-81b1-8f39e04f36bd.png">

**Comment by 19960117yusuke** [comment]
ありがとうございます！
全角スペースが入ってるとダメなんですね。

このエラーについては消えました！

**Comment by 19960117yusuke** [comment]
commit transactionが出たので成功したとみなしていいのかな。
これでチュートリアルの方の実装に向かいます。


```
Processing by UsersController#create as HTML
  Parameters: {"oauth_token"=>"UtFNzwAAAAAA6je7AAABY_jGyfI", "oauth_verifier"=>"6WdO7segPXeNxHEis2mVLyzQdTHm8LNV", "provider"=>"twitter"}
  User Load (1.6ms)  SELECT  "users".* FROM "users" WHERE "users"."provider" = ? AND "users"."uid" = ? LIMIT ?  [["provider", "twitter"], ["uid", "971764922366349312"], ["LIMIT", 1]]
   (0.1ms)  begin transaction
  SQL (3.6ms)  INSERT INTO "users" ("provider", "uid", "user_name", "image_url", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["provider", "twitter"], ["uid", "XXXXXXXX"], ["user_name", "XXXXXXXXXXXXXXX"], ["image_url", "XXXXXXXXXXXXXXXXX"], ["created_at", "2018-06-13 10:52:49.420428"], ["updated_at", "2018-06-13 10:52:49.420428"]]
   (2.7ms)  commit transaction
Redirected to http://127.0.0.1:3000/posts/index
```

**Comment by ladnack** [comment]
```
$ rails console
```

でDBにデータ保存されたか確認できる

```
> User.all 
```

**Comment by 19960117yusuke** [comment]
ありがとうございます。
保存されてました！

**Comment by 19960117yusuke** [comment]
メモ

twitterからのデータ取得は可能になっている。

が、UserのDBにsaveする段階でひっかっている。
rollback transactionがおきている。
・emailは登録しないと取れない
・gravatarのエラーなど

→一度validatationを取ってやってみる。

**Comment by 19960117yusuke** [comment]
![2018-06-14 12 00 22](https://user-images.githubusercontent.com/35832220/41389505-2e14eec6-6fcc-11e8-9bf8-ef2a59a55c8d.png)
→
![2018-06-14 12 00 34](https://user-images.githubusercontent.com/35832220/41389502-2dea3adc-6fcc-11e8-9fc2-a01fb0d790b9.png)

**Comment by 19960117yusuke** [comment]
できたこと
-twitter連携ログイン

できなかったこと
-ログインボタンの配置修正

**Comment by ladnack** [comment]
[Q] sign up 時はTwitterでできない？

**Comment by 19960117yusuke** [comment]
>[Q] sign up 時はTwitterでできない？

[A]sign up時もできます。追記しておきました。

**Comment by 19960117yusuke** [comment]
ありがとうございます！そうですね！

![2018-06-17 16 41 39](https://user-images.githubusercontent.com/35832220/41505895-93afa0e0-724d-11e8-9455-47cbf190fc69.png)


追加しました！
