### ISSUE TITLE
DM機能の実装

### ISSUE THREAD

**Issue by 19960117yusuke** [ookamiinc/rails_tutorial_app#27]
明日作成。

**Comment by 19960117yusuke** [comment]
- DMの流れ
    - users#showでDMリンクをクリック
　-  current_userとuserでRoomが作られる。room/:room_idにリダイレクト。
　-  そこでメッセージを投稿。



 - [ ]  users#showからのリンク。これはPostで送って、roomモデルができたらそこにリダイレクトする構想。
　　　- [ ] アクセス制限。

 - [ ]  Roomモデルの作成
     -  [ ]  user_id, other_user_id

      - [ ]     Userモデルとのアソシエーション
　  -  [ ]     ２つの組み合わせがunque:trueになるように。user_idが若い方をuser_idの方に格納するなどのルールが必要か。
 - [ ]       Messageモデルの作成
　  -  [ ]      user_id, room_id,contentを持つ。
　   -  [ ]       アソシエーション
 - [ ]   Messageのform
        - [ ] View current_userとparamsでroom_id,content
  -[ ]   Messageの表示　
　　- [ ]  room.messagesでorder_byのcreated_at
       - [ ] contentとuser名,userへのリンク、写真を送る

**Comment by 19960117yusuke** [comment]
![2018-06-17 11 50 34](https://user-images.githubusercontent.com/35832220/41504268-adcd8e0c-7224-11e8-920b-2539bdb78c14.png)

![2018-06-17 11 49 51](https://user-images.githubusercontent.com/35832220/41504267-9980bc08-7224-11e8-8d8b-3ca2251d9196.png)

できたこと
・users#showからDMへのリンク。
・ユーザーはDMを投稿できる。
・DMを確認できる

できていないこと
・自分が投稿しているのに、別のユーザーの投稿となる（重要なバグ)
・CSSの調整(DM感を出す)

**Comment by ladnack** [comment]
> 自分が投稿しているのに、別のユーザーの投稿となる（重要なバグ)

余裕あったら直そうか🙃

**Comment by 19960117yusuke** [comment]
Yusukeにてコメント追加後。
![2018-06-17 15 59 26](https://user-images.githubusercontent.com/35832220/41505610-75bc8bee-7247-11e8-8bf1-75f738e577dd.png)
