### ISSUE TITLE
プロフィール文機能の実装

### ISSUE THREAD

**Issue by yusuko** [ookamiinc/rails_tutorial_app#5]
ユーザーはプロフィール文を作成・更新できるようにする。
プロフィール文は登録時はnil,ログイン後にusers#editから編集。

変更箇所

- DB
    -  プロフィールの追加
- Model
    -  バリデーション
- View
    -  users#edit
    -  render 'shared/user_info'の更新
          -  static-pages#home
          -  users#show
- Controller
    -  users#update

**Comment by 19960117yusuke** [comment]
まずはDBの作成から行なっていきます。

**Comment by ladnack** [comment]
issue を close する前に何がどう変わったかスクショで貼ってもらえるとわかりやすいです👀

<img width="499" alt="screenshot" src="https://user-images.githubusercontent.com/19564003/41190876-6818571a-6c21-11e8-8093-f46f767c9c49.png">

**Comment by 19960117yusuke** [comment]
了解です！
今後そうします！
